import { prisma } from "@/lib/prisma"
import * as judges from "./data/judges"
import * as competitors from "./data/competitors"
import * as tipos_estandarte from "./data/tipos_estandarte"
import * as events from "./data/events"

async function seed(){

    /* JURADOS */
    await prisma.judge.createMany({data:[
        judges.smee,
        judges.tiao,
        judges.buiu,
        judges.lukinhas,
        judges.saviani,
        judges.cirilo,
        judges.ze_gois,
        judges.persa,
        judges.lessa,
        judges.feijo,
        judges.carlitoz,
        judges.cego,
        judges.moleza,
        judges.lu_vanini,
        judges.zoinho,
        judges.tigues,
        judges.chilli,
        judges.yan_piscerne,
        judges.gabs_almeida,
        judges.chaique,
        judges.zedu,
        judges.brisa,
        judges.tieta,
        judges.franci,
        judges.mari_farias,
        judges.galeazzi
    ],
    skipDuplicates: true
    })
    /* Baterias */
    await prisma.competitor.createMany({
        data:
        [
        competitors.batera_do_inferno,
        competitors.bateria_51,
        competitors.bateria_UFMG,
        competitors.bateria_arritmia,
        competitors.bateria_artilharia,
        competitors.bateria_atômica,
        competitors.bateria_ausculta,
        competitors.bateria_avalanche,
        competitors.bateria_azzurra,
        competitors.bateria_azzurra_2,
        competitors.bateria_bandida,
        competitors.bateria_batereca,
        competitors.bateria_batimeduca,
        competitors.bateria_batucateia,
        competitors.bateria_brejodum,
        competitors.bateria_brocadora,
        competitors.bateria_bruteria,
        competitors.bateria_c7,
        competitors.bateria_cachorro_manco,
        competitors.bateria_carniceiros,
        competitors.bateria_carniceria,
        competitors.bateria_cascuda,
        competitors.bateria_casper,
        competitors.bateria_charanga,
        competitors.bateria_cherateria,
        competitors.bateria_cilada,
        competitors.bateria_codebloco,
        competitors.bateria_computaria,
        competitors.bateria_danada,
        competitors.bateria_dentadura,
        competitors.bateria_einsteria,
        competitors.bateria_enfernalha,
        competitors.bateria_epidemia,
        competitors.bateria_esparteria_jjm,
        competitors.bateria_espm,
        competitors.bateria_farmatuque,
        competitors.bateria_federais,
        competitors.bateria_fura_capilar,
        competitors.bateria_furiosa_cp,
        competitors.bateria_furiosa_verde,
        competitors.bateria_gaperia,
        competitors.bateria_histeria,
        competitors.bateria_homunculoco,
        competitors.bateria_hooligans,
        competitors.bateria_imperial,
        competitors.bateria_incendiaria,
        competitors.bateria_incendiaria_vermelha,
        competitors.bateria_infanteria,
        competitors.bateria_insana,
        competitors.bateria_intravenosa,
        competitors.bateria_invasora,
        competitors.bateria_jabuteria,
        competitors.bateria_limeteria,
        competitors.bateria_lobateria_guara,
        competitors.bateria_lobateria_sjc,
        competitors.bateria_lobateria_ufsj,
        competitors.bateria_los_borrachos,
        competitors.bateria_maculosa,
        competitors.bateria_mafia_academica,
        competitors.bateria_mafiosa,
        competitors.bateria_maloca,
        competitors.bateria_malvadeza,
        competitors.bateria_mamuteria,
        competitors.bateria_manda_chuva,
        competitors.bateria_medbloco,
        competitors.bateria_mercenaria,
        competitors.bateria_meritissima,
        competitors.bateria_muquirana,
        competitors.bateria_naumteria,
        competitors.bateria_necromante,
        competitors.bateria_os_coringas,
        competitors.bateria_percursao,
        competitors.bateria_pirateria,
        competitors.bateria_predadora,
        competitors.bateria_predadora_ufla,
        competitors.bateria_primata,
        competitors.bateria_psicolata,
        competitors.bateria_puteria,
        competitors.bateria_rapozona,
        competitors.bateria_rateria,
        competitors.bateria_reicapau,
        competitors.bateria_sa,
        competitors.bateria_sancabum,
        competitors.bateria_suprema,
        competitors.bateria_tatubola,
        competitors.bateria_taubateria,
        competitors.bateria_toro_loko,
        competitors.bateria_tourada,
        competitors.bateria_tubatuque,
        competitors.bateria_ufscar,
        competitors.bateria_ufuteria,
        competitors.bateria_vaca_magra,
        competitors.bateria_xoxoteria,
        competitors.bateria_logaritma,
        competitors.bateria_batucacef,
        competitors.bateria_amedronta,
        competitors.bateria_malandragem,
        competitors.bateria_batucarara,
        competitors.bateria_mafia_guaxi,
        competitors.bateria_transtorna,
        competitors.bateria_besouteria,
        competitors.bateria_vira_lata,
        competitors.bateria_maquinada,
        competitors.bateria_majestosa,
        competitors.bateria_integrada,
        competitors.bateria_filormonica,
        competitors.bateria_estouro,
        competitors.bateria_charanga_primata,
        competitors.bateria_enigmatica,
        competitors.bateria_charanga_pandemia,
        competitors.bateria_bateruja,
        competitors.bateria_grosseria,
        competitors.bateria_medusa,
        competitors.bateria_engrenada,
        competitors.bateria_cachacina,
        competitors.bateria_fumarato,
        competitors.bateria_dogteria,
        competitors.bateria_apucalipse,
        competitors.bateria_psicose,
        competitors.bateria_apgar_10,
        competitors.bateria_demonios_da_lagoa,
        competitors.bateria_oloduck,
        competitors.bateria_minotrago,
        competitors.bateria_gorilada,
        competitors.bateria_panterada,
        competitors.bateria_madrasta,
        competitors.bateria_tagarela,
        competitors.bateria_venenosa_ufg,
        competitors.bateria_dramatica,
        competitors.bateria_sanguinaria,
        competitors.bateria_cachorrada,
        competitors.bateria_batucada_samba_clube,
    ],
        skipDuplicates:true}
    )
    /* Eventos */
    await prisma.event.createMany({data:[
        events.cia_2025_3_div,
        events.cia_2025_2_div,
        events.cia_2025_1_div,
        events.pre_seletiva_balatucada_25,
        events.principal_balatucada_25,
        events.seletiva_balatucada_25,
        events.unigames_25,
        events.engenhariadas_pr_25,
        events.o_maior_inter_25
    ],skipDuplicates:true})

    // CIA 3ª Div 25
    await events.addCompToEvent(
        [
            competitors.bateria_logaritma.id, 
            competitors.bateria_batucacef.id,
            competitors.bateria_dentadura.id,
            competitors.bateria_amedronta.id,
            competitors.bateria_malandragem.id,
            competitors.bateria_toro_loko.id,
            competitors.bateria_batucarara.id,
            competitors.bateria_cachorrada.id,
            competitors.bateria_mafia_guaxi.id,
            competitors.bateria_transtorna.id,
            competitors.bateria_besouteria.id,
            competitors.bateria_vira_lata.id,
            competitors.bateria_maquinada.id
        ],
        events.cia_2025_3_div.id
    )
    await judges.addJudgesToEvent(
        [
            judges.brisa.id,
            judges.chilli.id,
            judges.tigues.id,
            judges.yan_piscerne.id
        ], 
        events.cia_2025_3_div.id
    )
    await events.createEventResults(
        events.cia_2025_3_div.id,
        [
            {
                id:competitors.bateria_logaritma.id,
                score:77.56
            },
            {
                id:competitors.bateria_batucacef.id,
                score:71.17
            },
            {
                id:competitors.bateria_dentadura.id,
                score:70.98
            },
            {
                id:competitors.bateria_amedronta.id,
                score:70.37
            },
            {
                id:competitors.bateria_malandragem.id,
                score:68.45
            },
            {
                id:competitors.bateria_toro_loko.id,
                score:68.40
            },
            {
                id:competitors.bateria_batucarara.id,
                score:67.63
            },
            {
                id:competitors.bateria_cachorrada.id,
                score:66.31
            },
            {
                id:competitors.bateria_mafia_guaxi.id,
                score:65.82
            },
            {
                id:competitors.bateria_transtorna.id,
                score:65.75
            },
            {
                id:competitors.bateria_besouteria.id,
                score:64.76
            },
            {
                id:competitors.bateria_vira_lata.id,
                score:64.73
            },
            {
                id:competitors.bateria_maquinada.id,
                score:63.47
            }
        ]
    )

    // CIA 2ª Div 25
    await events.addCompToEvent(
        [
            competitors.bateria_predadora.id, 
            competitors.bateria_meritissima.id,
            competitors.bateria_computaria.id,
            competitors.bateria_mercenaria.id,
            competitors.bateria_danada.id,
            competitors.bateria_majestosa.id,
            competitors.bateria_integrada.id,
            competitors.bateria_filormonica.id,
            competitors.bateria_estouro.id,
            competitors.bateria_charanga_primata.id,
            competitors.bateria_enigmatica.id,
            competitors.bateria_charanga_pandemia.id,
            competitors.bateria_bateruja.id,
            competitors.bateria_grosseria.id
        ],
        events.cia_2025_2_div.id
    )
    await judges.addJudgesToEvent(
        [
            judges.lukinhas.id,
            judges.tieta.id,
            judges.tigues.id,
            judges.yan_piscerne.id
        ],
        events.cia_2025_2_div.id
    )
    await events.createEventResults(
        events.cia_2025_2_div.id,
        [
            {
                id:competitors.bateria_predadora.id,
                score:77.81
            },
            {
                id:competitors.bateria_meritissima.id,
                score:77.13
            },
            {
                id:competitors.bateria_computaria.id,
                score:75.39
            },
            {
                id:competitors.bateria_mercenaria.id,
                score:74.70
            },
            {
                id:competitors.bateria_danada.id,
                score:72.73
            },
            {
                id:competitors.bateria_majestosa.id,
                score:72.20
            },
            {
                id:competitors.bateria_integrada.id,
                score:71.66
            },
            {
                id:competitors.bateria_filormonica.id,
                score:70.59
            },
            {
                id:competitors.bateria_estouro.id,
                score:70.31
            },
            {
                id:competitors.bateria_charanga_primata.id,
                score:69.97
            },
            {
                id:competitors.bateria_enigmatica.id,
                score:68.64
            },
            {
                id:competitors.bateria_charanga_pandemia.id,
                score:67.03
            },
            {
                id:competitors.bateria_bateruja.id,
                score:65.86
            },
            {
                id:competitors.bateria_grosseria.id,
                score:62.87
            },
        ]
    )

    // CIA 1ª Div 25
    await events.addCompToEvent(
        [
            competitors.bateria_artilharia.id, 
            competitors.bateria_medusa.id,
            competitors.bateria_engrenada.id,
            competitors.bateria_cachacina.id,
            competitors.bateria_charanga.id,
            competitors.bateria_fumarato.id,
            competitors.bateria_dogteria.id,
            competitors.bateria_apucalipse.id,
            competitors.bateria_incendiaria.id,
            competitors.bateria_psicose.id,
            competitors.bateria_apgar_10.id,
        ],
        events.cia_2025_1_div.id
    )
    await judges.addJudgesToEvent(
        [
            judges.buiu.id,
            judges.lukinhas.id,
            judges.tieta.id,
            judges.tigues.id,
            judges.brisa.id,
            judges.yan_piscerne.id
        ], 
        events.cia_2025_1_div.id
    )
    await events.createEventResults(
        events.cia_2025_1_div.id,
        [
            {
                id:competitors.bateria_artilharia.id,
                score:79.28
            },
            {
                id:competitors.bateria_medusa.id,
                score:77.07
            },
            {
                id:competitors.bateria_engrenada.id,
                score:76.22
            },
            {
                id:competitors.bateria_cachacina.id,
                score:75.78
            },
            {
                id:competitors.bateria_charanga.id,
                score:74.74
            },
            {
                id:competitors.bateria_fumarato.id,
                score:74.06
            },
            {
                id:competitors.bateria_dogteria.id,
                score:73.02
            },
            {
                id:competitors.bateria_apucalipse.id,
                score:72.17
            },
            {
                id:competitors.bateria_incendiaria.id,
                score:72.02
            },
            {
                id:competitors.bateria_psicose.id,
                score:71.93
            },
            {
                id:competitors.bateria_apgar_10.id,
                score:70.18
            },
        ]
    )

    // ENGENHARIADAS PR 25
    await events.addCompToEvent(
        [
            competitors.bateria_epidemia.id, 
            competitors.bateria_c7.id,
            competitors.bateria_demonios_da_lagoa.id,
            competitors.bateria_carniceiros.id,
            competitors.bateria_tourada.id,
            competitors.bateria_rapozona.id,
            competitors.bateria_oloduck.id,
            competitors.bateria_minotrago.id,
            competitors.bateria_gorilada.id,
            competitors.bateria_panterada.id
        ],
        events.engenhariadas_pr_25.id
    )
    await judges.addJudgesToEvent(
        [
            judges.lu_vanini.id,
            judges.moleza.id,
            judges.saviani.id,
            judges.galeazzi.id
        ], 
        events.engenhariadas_pr_25.id
    )
    await events.createEventResults(
        events.engenhariadas_pr_25.id,
        [
            {
                id:competitors.bateria_epidemia.id,
                score:39.56
            },
            {
                id:competitors.bateria_c7.id,
                score:39.24
            },
            {
                id:competitors.bateria_demonios_da_lagoa.id,
                score:39.1
            },
            {
                id:competitors.bateria_carniceiros.id,
                score:39.05
            },
            {
                id:competitors.bateria_tourada.id,
                score:38.83
            },
            {
                id:competitors.bateria_rapozona.id,
                score:38.56
            },
            {
                id:competitors.bateria_oloduck.id,
                score:36.05
            },
            {
                id:competitors.bateria_minotrago.id,
                score:35.44
            },
            {
                id:competitors.bateria_gorilada.id,
                score:34.73
            },
            {
                id:competitors.bateria_panterada.id,
                score:34.3
            }
        ]
    )

    await prisma.bannerType.createMany(
        {
            data:[
                tipos_estandarte.agogo,
                tipos_estandarte.caixa ,
                tipos_estandarte.chocalho ,
                tipos_estandarte.complementar ,
                tipos_estandarte.marcacao ,
                tipos_estandarte.mestre ,
                tipos_estandarte.repique ,
                tipos_estandarte.tamborim ,
                tipos_estandarte.terceira ,
                tipos_estandarte.torcida ,
            ],
            skipDuplicates: true
        }
    )
}


seed().then(()=>{
    console.log('Database seeded')
    prisma.$disconnect()
})